BookFinder/Models/ErrorViewModel.cs
using System;

namespace BookFinder.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

BookFinder/Controllers/AddBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookFinder.Apllication.Interfaces;
using BookFinder.Apllication.ViewModels;
using BookFinder.Application.Interfaces;
using BookFinder.Application.ViewModels;
using BookFinder.Domain.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace BookFinder.Controllers
{
    [Authorize]
    public class AddBookController : Controller
    {
        
        public IAddBook _addBook;
        public AddBookController(IAddBook addBook)
        {
            _addBook = addBook;
            
        } 
        public IActionResult AddPage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddBook(Book newBook)
        {
            bool status = _addBook.AddBook(newBook);
            if (status)
            {
                return RedirectToAction("Library", "Library");
            }
            else
            {
                return View("ErrorPage", "AddBook");
            }
            
        }
    }
}

BookFinder/Controllers/BookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookFinder.Apllication.Interfaces;
using BookFinder.Apllication.ViewModels;
using Microsoft.AspNetCore.Mvc;

namespace BookFinder.Controllers
{
    public class BookController : Controller
    {
        private IBookService _bookService;
        public BookController(IBookService bookService)
        {
            _bookService = bookService;
        }
        public IActionResult Index()
        {
            BookViewModel model = _bookService.GetBooks();
            return View(model);
        }
    }
}

BookFinder/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using BookFinder.Models;

namespace BookFinder.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

BookFinder/Controllers/LibraryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookFinder.Apllication.Interfaces;
using BookFinder.Apllication.ViewModels;
using BookFinder.Application.Interfaces;
using BookFinder.Application.ViewModels;
using BookFinder.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookFinder.Controllers
{
    public class LibraryController : Controller
    {
        private IBookService _bookService;        
        public LibraryController(IBookService bookService)
        {
            _bookService = bookService;
            
        }
        
        public IActionResult Library()
        {
            BookViewModel model = _bookService.GetBooks();
            return View(model);
        }        
    }
}

BookFinder/Controllers/SearchBookController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BookFinder.Apllication.Interfaces;
using BookFinder.Apllication.ViewModels;
using BookFinder.Application.Interfaces;
using BookFinder.Application.ViewModels;
using BookFinder.Domain.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookFinder.Controllers
{
    public class SearchBookController : Controller
    {
        private ISearchBook _searchBook;
        
        public SearchBookController(ISearchBook searchBook)
        {
            _searchBook = searchBook;
        } 
        public IActionResult SearchPage()
        {
            return View();
        }
        [HttpPost]
        public IActionResult SearchBook(string keyword)
        {
            SearchBookViewModel model = _searchBook.GetSearchResult(keyword);
            return View(model);
        }
    }
}

BookFinder/Views/AddBook/AddPage.cshtml
<div class="container container-fluid">
    <h4>Wanna add to our collection? Feel Free!</h4>
    <small>We thank you for taking time out and helping us grow.</small>
    <br /> <br />
</div>


<div class="container container-fluid">
    <form method="post" action ="/AddBook/AddBook">
        <div class="form-group">
            <label for="ISBN">ISBN:</label>
            <input type="text" name ="isbn"class="form-control" id="ISBN" aria-describedby="ISBNHelp" required>
            <small id="ISBNHelp" class="form-text text-muted">An ISBN is a textual string which uniquely identifies a publication.</small>
        </div>
        <div class="form-group">
            <label for="name">Book Name:</label>
            <input type="text" name ="name"class="form-control" id="name" aria-describedby="BookName" required>
            <small id="BookName" class="form-text text-muted">Name of the book you want to add to our library!</small>
        </div>
        <div class="form-group">
            <label for="Author">Author:</label>
            <input type="text" name ="author"class="form-control" id="Author" aria-describedby="AuthorHelp" required>
            <small id="AuthorHelp" class="form-text text-muted">Author of the publication</small>
        </div>
        <div class="form-group">
            <label for="Publisher">Publisher:</label>
            <input type="text" name ="publisher"class="form-control" id="Publisher" aria-describedby="PublisherHelp" required>
            <small id="PublisherHelp" class="form-text text-muted">Name of the publishing House</small>
        </div>
        <div class="form-group">
            <label for="Cost">Cost:</label>
            <input type="number" name ="cost" class="form-control" id="Cost" aria-describedby="CostHelp" required>
            <small id="CostHelp" class="form-text text-muted">Price of the publication.</small>
        </div>
        <div class="form-group">
            <label for="Description">Description:</label>
            <input type="text" name ="descriptuon" class="form-control" id="Description" aria-describedby="descHelp" required>
            <small id="dechHelp" class="form-text text-muted">A brief description of the publication to help our fellow users!</small>
        </div>
        
        <button type="submit" class="btn btn-success">Submit</button>
    </form>
</div>

BookFinder/Views/AddBook/ErrorPage.cshtml
<div class="container container-fluid">
    <h3>Something did not go right with that entry!</h3>
    <small>But we do think we can help you with what went wrong!</small>
    <br /><br />
</div>


<div class="container container-fluid">
    <div>
        <p>
            What we think might have happened:
            <ul>
                <li>The entry already exists in which case an ISBN duplication is detected by the system. Please check our library section <a asp-controller="Library" asp-action="Library">here</a> to see if the entry exists.</li>
                <li>There were uacceptable characters in the entry.</li>
            </ul>
        </p>
        <br /><br />
        <p>Please feel free to try again! Albeit with a little more care! Here, we'll even provide you with the <a asp-controller="AddBook" asp-action="AddPage">link</a>. We're cool like that!</p>
    </div>
</div>

BookFinder/Views/Book/Index.cshtml
@model BookFinder.Apllication.ViewModels.BookViewModel

    <div class="conatiner container-fluid">
        <h4>Here is all we have in the Inventory!</h4>
        <small>We hope we have what you're looking for!</small>
        <br /><br />
    </div>
    
   <div class="container body-content">
        <div class="row book-details">
            <table class="table table-striped">
                <thead class = "thead-dark">
                    <tr>
                        <td>ISBN</td>
                        <td>Name</td>
                        <td>Author Name</td>
                        <td>Publisher Name</td>
                        <td>Cost</td>
                        <td>Description</td>
                    </tr>
                </thead>
                <tbody>            
                @foreach (var bookData in Model.Books)
                {
                    <div class="book-container">

                        <tr>
                            <td>@bookData.isbn </td>
                            <td>@bookData.name </td>
                            <td>@bookData.author </td>
                            <td>@bookData.publisher </td>
                            <td>@bookData.cost </td>
                            <td>@bookData.descriptuon </td>
                        </tr>

                    </div>
                }
                </tbody>
            </table>
            </div>

    </div>
   <br /><br />
   <div class="conatiner container-fluid">
       <h6>Be Sure to head over to our search page on the navbar if you're looking for something specfic or add a book to this library if you want to contribute!</h6>
   </div>

BookFinder/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Book Finder";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Welocome to online Library Portal</p>
</div>

BookFinder/Views/Library/Library.cshtml
@model BookFinder.Apllication.ViewModels.BookViewModel

    <div class="conatiner container-fluid">
        <h4>Here is all we have in the Inventory!</h4>
        <small>We hope we have what you're looking for!</small>
        <br /><br />
    </div>
    
   <div class="container body-content">
        <div class="row book-details">
            <table class="table table-striped">
                <thead class = "thead-dark">
                    <tr>
                        <td>ISBN</td>
                        <td>Name</td>
                        <td>Author Name</td>
                        <td>Publisher Name</td>
                        <td>Cost($)</td>
                        <td>Description</td>
                    </tr>
                </thead>
                <tbody>            
                @foreach (var bookData in Model.Books)
                {
                        <tr>
                            <td>@bookData.isbn </td>
                            <td>@bookData.name </td>
                            <td>@bookData.author </td>
                            <td>@bookData.publisher </td>
                            <td>@bookData.cost </td>
                            <td>@bookData.descriptuon </td>
                        </tr>

                    
                }
                </tbody>
            </table>
            </div>

    </div>
   <br /><br />
   <div class="conatiner container-fluid">
       <h6>Be Sure to head over to our search page on the navbar if you're looking for something specfic or add a book to this library if you want to contribute!</h6>
   </div>

BookFinder/Views/SearchBook/SearchBook.cshtml
@model BookFinder.Application.ViewModels.SearchBookViewModel;

<div class="container container-fluid">
    <div class="container body-content">
        <div class="row book-details">
            @if (Model.SearchedBooks.Count != 0)
            {
                <div class="container container-fluid">
                    <h4>Here is what we found!</h4>
                    <small>We hope you found what you were looking for!</small>
                    <br /><br />
                </div>
                <table class="table table-striped">
                    <thead class="thead-dark">
                        <tr>
                            <td>ISBN</td>
                            <td>Name</td>
                            <td>Author Name</td>
                            <td>Publisher Name</td>
                            <td>Cost($)</td>
                            <td>Description</td>
                        </tr>
                    </thead>
                    <tbody>

                        @foreach (var bookData in Model.SearchedBooks)
                        {
                            <tr>
                                <td>@bookData.isbn </td>
                                <td>@bookData.name </td>
                                <td>@bookData.author </td>
                                <td>@bookData.publisher </td>
                                <td>@bookData.cost </td>
                                <td>@bookData.descriptuon </td>
                            </tr>


                        }
                    </tbody>
                </table>
            }
            @if (Model.SearchedBooks.Count == 0)
            {
                <p>Oops! Looks like we hit a brick wall there! No books or authors of the given search term were found! Wanna try again?</p>
            }
        </div>

    </div>
    <h6>If no data is found you can add books to our library <a asp-controller="AddBook" asp-action="AddPage">here</a></h6>
</div>

BookFinder/Views/SearchBook/SearchPage.cshtml
<div class="container container-fluid">
    <form method="post" action ="/SearchBook/SearchBook">
        <div class="form-group">
            <label for="keyword">Search Keyword:</label>
            <input type="text" name ="keyword"class="form-control" id="keyword" aria-describedby="keywordHelp" required>
            <small id="keywordHelp" class="form-text text-muted">Provide us with a name or atleast a part of it so that we can search our databases for you!</small>
        </div>
        <button type="submit" class="btn btn-success">Submit</button>
    </form>    
</div>

BookFinder/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookFinder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookFinder</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Library" asp-action="Library">Library</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AddBook" asp-action="AddPage">Add Book</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="SearchBook" asp-action="SearchPage">Search</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - BookFinder - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>